-- Table: stg.t_stg_go_retailers

DROP TABLE IF EXISTS det.t_dim_retailers;

CREATE TABLE IF NOT EXISTS det.t_dim_retailers
(
    dim_retailer_sk bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
    retailer_code bigint,
    retailer_name text,
    retailer_type text,
    country text,
    scd2_hash text,
    start_ts timestamptz,
    end_ts timestamptz,
    version_number integer,
    is_current boolean,
    prior_dim_retailer_sk bigint
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS det.t_dim_retailers
    OWNER to postgres;