DROP TABLE IF EXISTS det.t_dim_order_methods;

CREATE TABLE IF NOT EXISTS det.t_dim_order_methods
(	dim_order_method_sk bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
    order_method_code bigint,
    order_method_type text,
    scd_hash  bytea not null,
    create_ts timestamptz not null,
    update_ts timestamptz not null
)


TABLESPACE pg_default;

ALTER TABLE IF EXISTS det.t_dim_order_methods
    OWNER to postgres;