CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS det.t_dim_products;

CREATE TABLE IF NOT EXISTS det.t_dim_products
(
    dim_product_sk          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    product_number          bigint,
    product_line            text,
    product_type            text,
    product                 text,
    product_brand           text,
    product_color           text,

    -- Use exact-decimal for prices/costs (per best practice)
    unit_cost               numeric(19,2),
    unit_price              numeric(19,2),
    -- MD5 as raw 16-byte value
    scd2_hash               bytea NOT NULL,
    

    start_ts                timestamptz,
    end_ts                  timestamptz,
    version_number          integer,
    is_current              boolean,
    prior_dim_product_sk    bigint
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS det.t_dim_products
    OWNER TO postgres;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_t_dim_products_scd2_hash
  ON det.t_dim_products (scd2_hash);

CREATE UNIQUE INDEX IF NOT EXISTS ux_t_dim_products_current
  ON det.t_dim_products (product_number)
  WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS ux_t_dim_products_version
  ON det.t_dim_products (product_number, version_number);


-- Prevent overlapping SCD2 intervals per product

-- Ensures time windows don’t overlap for the same key—a great integrity guard for SCD2.

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE det.t_dim_products
  ADD CONSTRAINT ex_dim_products_no_overlap
  EXCLUDE USING gist (
    product_number WITH =,
    tstzrange(start_ts, end_ts, '[]') WITH &&
  );


