
DROP TABLE IF EXISTS det.t_fct_sales; 

CREATE TABLE IF NOT EXISTS det.t_fct_sales 
(
    fct_sales_sk bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    dim_retailer_sk bigint not null,
    dim_product_sk bigint not null,
    dim_order_method_sk bigint not null,
    transaction_date date not null,
    quantity integer not null,
    unit_price  numeric(19,2) not null,
    unit_sale_price numeric(19,2) not null,
    fact_hash bytea not null,
    create_ts timestamptz not null,
    update_ts timestamptz not null
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS det.t_fct_sales
    OWNER TO postgres;

